name: github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      # - name: Bulid Project
      - uses: actions/checkout@v2
      - run: mvn package
      - name: Exports the full file path
        id: file
        run: echo "::set-output name=path::$(realpath ./target/dcms-1.6.8-SNAPSHOT.war)"

      - uses: leandro-hermes/action-upload-file@v1.1.0
        with:
          host: 'httpbin.org'
          path: '/post'
          filePath: ${{ steps.file.outputs.path }}
          data: ${{ toJson(github.event.push) }}
      - run: echo github.event.push
